version: '3'
services:
  myapp-main:
    image: golf-club-tournament:latest
    ports:
      - 8080:8080
    environment:
     # - spring.datasource.url=jdbc:mysql://host.docker.internal:3306/tournament_db_2024
      - spring.datasource.url=jdbc:mysql://golf-club-tour-instance-1.cj3urig8rllm.us-east-1.rds.amazonaws.com/golf_club
      - spring.datasource.password=bluemaptapcap67!
      - spring.datasource.username=admin